import express from "express";
import rotaUsuario from "./rotas/rotas-usuarios.js";

const app = express();
app.use(express.json());

app.use('/usuarios', rotaUsuario);

app.listen(3000);

/*
DELETAR

PRECISA DO ID DO USUÁRIO A SER DELETADO
- TRANFORMAR O ID DE STRING PARA NÚMERO
- SE O ID FOR INVALIDO, RETORNA 400
- VERIFICAR SE O USUÁRIO EXISTE
- SE NÃO EXISTIR, RETORNAR 404
 */

/*
ATUALIZAR

PRECISA DO ID DO USUÁRIO A SER ATUALIZADO
- TRANFORMAR O ID DE STRING PARA NÚMERO
- SE O ID FOR INVALIDO, RETORNA 400

- PROCURAR O USUÁRIO DENTRO DO ARRAY -> FIND
- SE NÃO EXISTIR, RETORNAR 404

- PRECISA DOS DADOS PARA ATUALIZAR (NOME OU EMAIL)
- PEGAR OS DADOS DO BODY (IGUAL O CREATE)
- SE NAO TIVER NENHUM DOS DADOS QUE PRECISAMOS, RETORNAR 400

-CASO TENHA EMAIL, VERIFICAR SE JÁ EXISTE UM USUÁRIO COM ESSE EMAIL -> SOME
- SE SIM, RETORNAR 409 -> CONFLITO

- DANDO TUDO CERTO
- NOME DO USUARIO ATUALIZADO
- EMAIL DO USUARIO ATUALIZADO
*/

/*
BOAS PRATICAS
- USAR A MESMA ROTA
*/ 